
---
title: Libera Ideoj
description: >
author: Joseph Anthony Pasquale Holsten
email: joseph@josephholsten.com
twitter_username: josephholsten
github_username:  josephholsten
url: "http://blog.josephholsten.com" # the base hostname & protocol for your site

theme: minima
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 10
